### ISSUE TITLE
[Propuesta charla] Introducción a la persistencia políglota

### ISSUE THREAD

**Issue by revington** [benidormtech/talks#1]
# Title / Título
Introducción a la persistencia políglota
# Description / Descripción
"Persistencia políglota" Significa usar distintos modelos de persistencia (distintas bases de datos) en función del uso que vayamos a hacer de los datos.
La persistencia políglota, por sus enormes beneficios, viene siendo usada desde hace años por infinidad de empresas punteras tales como FB, Spotify o Instagram entre otras.
Además esta tendencia se está consolidando en organizaciones de menor envergadura gracias a su coste relativamente bajo.

En esta charla explicaremos en qué consiste la persistencia políglota así como sus beneficios y costes.
Analizaremos casos de uso que son aplicables en gran medida a arquitecturas web existentes.
También daremos algunos consejos sobre cómo preparar tu próximo MVP para la persistencia políglota a coste 0.
# Speaker Bio / Bio del Ponente
[Pedro Narciso García Revington](https://github.com/revington), [LinkedIn](https://www.linkedin.com/in/revington/)
# Level / Nivel
Intermedio

# Duration / Duración
45'

# Constraints / Condicionantes
--

**Comment by xgalen** [comment]
Genial. Gracias por la propuesta. ¿Qué te parecería hacerla en mayo? Por ejemplo, el viernes 17 ó 24 por la tarde.

**Comment by xgalen** [comment]
Programada https://www.meetup.com/es-ES/Benidorm-Tech-Meetup/events/267752232/

**Comment by xgalen** [comment]
Fue un éxito. La cierro :D
